name: game-off-2012
description: Entry to the GitHub Game Off 2012
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>
homepage: https://github.com/denniskaselow/game-off-2012
dependencies:
  dartemis:
    git: git://github.com/denniskaselow/dartemis.git