name: spaceoff
author: Dennis Kaselow <Dennis.Kaselow+githubgameoff2012@gmail.com>
description: Entry to the GitHub Game Off 2012
homepage: https://github.com/denniskaselow/game-off-2012
dependencies:
  browser: any
  dartemis:
      git:
        url: git://github.com/denniskaselow/dartemis.git
        ref: develop
  dartemis_transformer:
    path: ../dartemis_transformer
  canvas_query: any
  lawndart: any
  dart_to_js_script_rewriter: ^1.0.2
transformers:
- dart_to_js_script_rewriter
- dartemis_transformer